
[Damage-Module]
	#The purpose of the damage module is to remove the invulnerability ticks after an entity is damaged to better suit gameplay where entities are going to be ignoring too much damage if left unchecked. Disabling will nullify every feature listed under this module.
	damageModuleEnabled = false
	#Some entities or damage sources rely on damage ticks to time their attacks. In these cases, we want to let them initiate i-frames.
	#entityBlacklist default: ["minecraft:slime","minecraft:ender_dragon","minecraft:magma_cube","irons_spellbooks:wall_of_fire","irons_spellbooks:void_tentacle"]
	entityBlacklist = ["minecraft:slime", "minecraft:ender_dragon", "minecraft:magma_cube", "irons_spellbooks:wall_of_fire", "irons_spellbooks:void_tentacle"]
	#damagesourceBlacklist default: ["lava","inFire","cactus","inWall","hotFloor","lightningBolt","sweetBerryBush","outOfWorld","drown"]
	damagesourceBlacklist = ["lava", "inFire", "cactus", "inWall", "hotFloor", "lightningBolt", "sweetBerryBush", "outOfWorld", "drown"]
	#Invulnerability Tick (I-Frame) count. Default: 0 (Vanilla's is 20, one second)
	invulnerabilityTickCount = 0
	#Specialized handling for player damage ticks. "ALL" means there is no special handling, "ONLY_LIVING" means only living attacks ignore player i-frames (may help with unforeseen damage like potions), and "NONE" means player's damage ticks are unaffected by the damage module.
	#Allowed Values: ALL, ONLY_LIVING, NONE
	playerDamageMode = "ALL"
	#In order to prevent spam attacks, a minimum threshold of attack strength can be set before an attack can deal damage. Default: 0.75
	minimumAttackStrength = 0.75
	#Whether or not a player is allowed to even swing if the threshold is not met. Default: true
	allowNonFullStrengthAttacks = true
	#Global multiplier to all knockback. Default: 1.0
	globalKnockbackMultiplier = 1.0

[Durability-Module]
	#The purpose of the durability module is to rework how durability damage is applied to better emulate an rpg setting.  Disabling will nullify every feature listed under this module.
	durabilityModuleEnabled = false
	#What type of gear should take vanilla durability damage. Default: NONE
	#Allowed Values: ALL, TOOLS, ARMOR, NONE
	vanillDurabilityGearType = "NONE"
	#What type of gear is damaged upon death. Default: ALL
	#Allowed Values: ALL, TOOLS, ARMOR, NONE
	deathGearType = "ALL"
	#The percent of durability damage equipment should take on player dying. Set to 0 to disable. Default: 0.15 (15%)
	durabilityLostOnDeath = 0.15
	#An additional constant amount of damage taken on death. This makes items with a high max durability degrade relatively slower. Set to 0 to disable. Default: 25
	additionalDurabilityLostOnDeath = 25

[XP-Module]
	#The purpose of the xp module is to rework how experience is dropped on a player's death by creating a souls-like xp catalyst instead. Disabling will nullify every feature listed under this module.
	xpModuleEnabled = false
	#Whether or not players will drop xp despite keepInventory gamerule. Default: true
	ignoreKeepInventory = true
	#Whether or not the player who dropped the xp is the only player allow to collect the xp. Default: true
	onlyAllowOwnerPickup = true
	#Multiplier to experience dropped by slain entities. Default: 1.0
	mobDropXpMultiplier = 1.0
	#Multiplier to experience dropped by blocks broken. Default: 1.0
	blockDropXpMultiplier = 1.0

[Enchantment-Module]
	#The purpose of the enchantment module is to mystify enchantments and add an additional challenge to game by obscuring the description of enchanted and cursed items found through looting. Disabling will nullify every feature listed under this module.
	enchantmentModuleEnabled = true
	#Whether or not armor should be automatically identified when equipped. Default: true
	identifyOnEquip = true
	#Whether or not unidentified items can be identified by interacting with an enchanting table. Default: true
	identifyOnEnchantingTable = true
	#Whether or not the enchanting table's functionality should be disabled, making looting or trading the only way to get enchanted items. Default: false
	disableEnchantingTable = false

[Hunger-Module]
	#The hunger module removes hunger and makes food to directly heal in order to to remove the tedious task of maintaining hunger, as well as rebalance health management during combat and exploration. Disabling will nullify every feature listed under this module.
	hungerModuleEnable = false
	#Disable Hunger. Without this, most of the hunger module features and config are nullified, but if you want to adjust stack sizes or potion mechanics without disabling hunger, you can do so here.
	disableHunger = true
	#The multiplier of a food's hunger value to health regained by eating it. Default: 0.5 (50%)
	foodToHealthModifier = 0.5
	#The amount of time, in ticks, between players naturally regenerating 1 hp. 1 second is 20 ticks. Turn off the naturalRegeneration gamerule to disable. Default: 250.
	naturalRegenerationTickRate = 250
	#Changes the stack size of potions. Set to 0 to disable. Requires game restart. Default: 4
	potionStackSize = 4
	#Limit the stack size of every food item. Set to 0 to disable. Requires game restart. Default: 0
	foodStackSize = 0
	#A Blacklist for limited food stack size, if enabled. Useful for mob drops or other edible items that are not meant as food. Default: ["minecraft:rotten_flesh","minecraft:spider_eye","minecraft:potato","minecraft:carrot","farmersdelight:onion","farmersdelight:tomato","farmersdelight:cabbage"]
	foodStackSizeBlacklist = ["minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:potato", "minecraft:carrot", "farmersdelight:onion", "farmersdelight:tomato", "farmersdelight:cabbage"]
	#Item Cooldown in seconds when throwing a splash potion. Default: 0.5
	splashPotionCooldown = 0.5
	#Item Cooldown in seconds when throwing a lingering potion. Default: 1.5
	lingeringPotionCooldown = 1.5

