
#Client configuration settings
[client]

	#In-game related options. These can be changed in game instead of config!
	[client.options]
		#If enabled, the player will render in the top left corner likes Bedrock Edition
		renderMiniPlayer = true
		#The controller icons to use in game to display actions
		controllerIcons = "DEFAULT"
		#If enabled, controller will be automatically selected on start up or when plugged in
		autoSelect = true
		#The sensitivity of the camera's pitch rotation when applying the rotation speed. Setting to 1.0 would mean applying 100% of the rotation speed.
		pitchSensitivity = 0.75
		#The distance you have to move the thumbstick before it's input is registered. This fixes drifting as some thumbsticks don't center to zero.
		deadZone = 0.1
		#Adjusts the camera sensitivity when looking through a spyglass
		spyglassSensitivity = 0.2
		#If enabled, the game will use a virtual cursor instead of the real cursor. This must be turned on to be able to run multiple instances!
		virtualMouse = true
		#The sensitivity of the camera's yaw rotation when applying the rotation speed. Setting to 1.0 would mean applying 100% of the rotation speed.
		yawSensitivity = 1.0
		#The speed which the cursor or virtual mouse moves around the screen
		mouseSpeed = 15.0
		#How much the trigger has to be pressed before it's input is registered. This fixes issues with triggers not being completely released to zero
		triggerDeadZone = 0.05
		#The image to use for the cursor. This only applies if virtual mouse is enabled!
		cursorType = "CONSOLE"
		#If enabled, allows you to craft quickly when clicking an item in the recipe book
		quickCraft = true
		#Draws a transparent background behind the text of the button hint
		hintBackground = true
		#If enabled, some gameplay elements will cause the controller to rumble
		rumble = true
		#The speed that lists scroll
		listScrollSpeed = 10.0
		#If enabled, plays a pop sound when you navigate in inventories, menus or scrolling the radial menu
		uiSounds = true
		#If enabled, inverts the controls on the Y axis for the camera
		invertLook = false
		#If enabled, inverts the controls on the X axis for the camera
		invertRotation = false
		#The thumbstick to use when scrolling items in the radial menu
		radialThumbstick = "RIGHT"
		#The speed which the camera turns in game
		rotationSpeed = 25.0
		#If enabled, hotbar will render closer to the center of the screen like on console.
		consoleHotbar = false
		#If enabled, shows common actions when displaying available on the screen
		showActions = "MINIMAL"
		#The scale of the mouse speed when hovering a widget or item slot
		hoverModifier = 0.6
		#Enabling this option will improve polling of controllers when your game FPS is capped. This will not have an effect if your game is already running at a low FPS without a cap.
		fpsPollingFix = false
		#The thumbstick that controls moving the cursor
		cursorThumbstick = "LEFT"

