
[GrassNotFloating]
	#Detection is processed based on the registry name of the block.
	#A registry name has three parts, namespace, path, and the separator colon
	#for example, `minecraft:grass` is a registry name, `minecraft` is its namespace, `grass` is its path, `:` is the separator colon
	#(1) and (2)'s values will be compare strictly and require an equal on detection
	#for (3), it's not strictly but use a `contains` check. For things like potato_grass, it will also works well
	"(1) Blocks That Should Not Float" = ["minecraft:grass"]
	"(2) Blocks That Should Not Float (Namespace Only)" = []
	"(3) Blocks That Should Not Float (Path Only)" = []

