
#Mystic's Biomes
#Common Config Center
["World Gen"]
	#The higher the number, the more common the biomes will be.
	#Default: 4
	"Biome Region Weight" = 4
	#Determines if each biome will generate or not.
	"Strawberry Fields" = true
	"Bamboo Blossom Forest" = true
	"Lavender Meadow" = true
	"Autumnal Grove" = true
	"Lush Oasis" = true
	Lagoon = false

["Animal Spawns"]
	#Biomes an animal can spawn in.
	#Values can include modded biomes and biome tags. example: "mysticsbiomes:strawberry_fields"
	"Rainbow Chickens" = ["minecraft:plains", "minecraft:forest", "minecraft:flower_forest"]
	#The chance an animal will spawn.
	#The higher the number, the more common an animal will spawn.
	#Default: 6
	"Rainbow Chicken Spawn Chance" = 6

