
[stressValues]

	#.
	#Fine tune the kinetic stats of individual components
	[stressValues.v2]
		#.
		#Stress impact of a powered brake [in Stress Units]
		#Range: -Infinity ~ Infinity
		brakeActiveStress = 16384.0

		#.
		#.
		#[in Stress Units]
		#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
		[stressValues.v2.impact]
			inverted_gearshift = 0.0
			six_way_gearbox = 0.0
			centrifugal_clutch = 0.0
			overstress_clutch = 0.0
			brake = 0.0
			encased_chain_cogwheel = 0.0
			inverted_clutch = 0.0
			parallel_gearbox = 0.0
			freewheel_clutch = 0.0
			brass_gearbox = 0.0
			shear_pin = 0.0

