
["Dog Constants"]
	#Disable hunger mode for the dog
	disable_hunger = false
	#When enabled you will spawn with a guide, Doggy Charm and Command Emblem.
	enable_starting_items = false
	#When enabled, dogs will be randomly assigned genders and will only mate and produce children with the opposite gender.
	enable_gender = true
	#When enabled, puppies get some levels from parents. When disabled, puppies start at 0 points.
	enable_pup_get_parent_levels = false
	#The time in ticks it takes for a baby dog to become an adult, default 48000 (2 Minecraft days) and minimum 0
	#Range: > 0
	time_to_mature = 48000
	#Determines if dogs should whine when hunger reaches below 20 DP.
	whine_when_hungry = true
	#When enabled, dogs will path and eat editable items in the world.
	eat_food_on_floor = true
	#When enabled, dogs cannot be killed by any mean (except creative-mode-bypass damage, in that case you can still respawn your dog using his linked bed or commands).
	#Instead, when his health reaches Zero, he will go into Incapacitated Mode.
	immortal_dogs = true
	#When enabled, dog can play tag with you. To make them play, throw a snowball at them.
	play_tag_with_dog = true
	#When enabled, dogs will start to miss you when you leave them for too long.
	#and when you come back, they will rush to you and greet you with love!
	dog_greet_owner = true
	#Specify how many dogs can greet you when you approach more than one missing dog.
	#The remaning dog will remain in their position.
	#To disable the limit, set this to any non-positive integer.
	#Although this will cause all of your dogs to stand up and greet.
	#YOU HAVE BEEN WARNED! :)
	#Range: > -2147483648
	dog_greet_owner_limit = 5
	#Option to disable dogs who mastered creeper sweeper and 
	#and are able to tackle creepers. This is helpful if players intend
	#their creeper sweeper master dogs to focus on fighting creeper instead of
	#warning, which may causes a bunch of false positive due to the range
	#is so wide that it includes creepers which are not in danger zone or not reachable.
	max_creeper_sweeper_dont_growl = true
	#Option to disable friendly fire for all players toward all dogs.
	#This is used to always be the case with friendly fire disabled for a single dog.
	all_player_cannot_attack_dog = false
	#Option to prevent dogs from accidentally go into a portal and get
	#unecessary transfered to another dimension, causing the owner having
	#to take them back. The prefered way to make a dog go to another dimension is
	#to have Cross Origin Teleport set to true on that dog.
	all_dog_block_portal = true
	#Define how many dogs a player can listen to commands which summon more than one dog to you
	#at the same time. Set this to any negative value to remove the limit completely.
	#Range: > -2147483648
	max_heel_limit = 20
	#Prevent dogs from pushing each other when navigating, this prevents dogs from pushing
	#another dog into a dangeruous area and improve navigation.
	prevent_dogs_pushing_each_other = true
	#Configure how many ticks it usually take for the dog to drop one hunger unit.
	#Range: > 10
	tick_per_hunger_dec = 400
	#Determine if the UUIDs of the dogs are being kept when training from vanilla
	#and when they respawn on bed. This also allows Duplication Detection.
	preserve_uuid = true
	#Duplication Detection
	#Specify what to do when a Duplication is detected when third parties are trying
	#to load the dog from their own copy.
	#Option are specified via the follwing Integer values
	#0 - Throw an exception out, this may produce a crash. However, this is the recommended way.
	#1 - Silently remove the dog.
	#Other - Do nothing.
	#Range: > -2147483648
	duplication_resolve_strategy = 0

