
#Server configuration settings
[server]
	#Set this to true to allow players to change the currency villagers accept
	villagerCanChangeCurrency = true
	#Set this to true to allow players to tax villagers
	villagerCanBeTaxed = true
	#Set this to true to allow players to bribe villagers
	villagerCanBeBribed = true
	#Chance that a magic ring will spawn in a dungeon/desert pyramid/jungle temple/buried treasure chest
	#Range: 0.0 ~ 1.0
	magicRingSpawnChance = 0.5

